FROM --platform=linux/amd64 ubuntu:24.04

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    vim \
    lsb-release \
    software-properties-common \
    ca-certificates \
    git \
    pkg-config \
    libssl-dev \
    libzmq3-dev \
    libprotobuf-dev \
    protobuf-compiler \
    libspdlog-dev \
    cmake \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*

RUN rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]